// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-RBnJfWOmutWtL7-dcSBdi7wzfgYpp5U',
    appId: '1:620090905986:web:110be3591485d99b302b9b',
    messagingSenderId: '620090905986',
    projectId: 'testing-72281',
    authDomain: 'testing-72281.firebaseapp.com',
    storageBucket: 'testing-72281.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC5eSzDLjMmW-APr5LLurJ7wql5p0pDJ4',
    appId: '1:620090905986:android:a328f7742a27980d302b9b',
    messagingSenderId: '620090905986',
    projectId: 'testing-72281',
    storageBucket: 'testing-72281.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAniF6ul6dc0WodjPemLyMbn0bpnijKhA',
    appId: '1:620090905986:ios:b37359964efb77a4302b9b',
    messagingSenderId: '620090905986',
    projectId: 'testing-72281',
    storageBucket: 'testing-72281.appspot.com',
    iosBundleId: 'com.example.testingprojectone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAniF6ul6dc0WodjPemLyMbn0bpnijKhA',
    appId: '1:620090905986:ios:a220e7bfd2f25246302b9b',
    messagingSenderId: '620090905986',
    projectId: 'testing-72281',
    storageBucket: 'testing-72281.appspot.com',
    iosBundleId: 'com.example.testingprojectone.RunnerTests',
  );
}
